# Generated by Django 3.0.4 on 2020-03-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200323_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Tag',
        ),
        migrations.AddField(
            model_name='products',
            name='Tag',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
