# Generated by Django 3.0.5 on 2020-04-22 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200420_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibo',
            old_name='date_created',
            new_name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='empleo',
            name='valor_dia',
        ),
        migrations.RemoveField(
            model_name='empleo',
            name='valor_hora',
        ),
    ]
