# Generated by Django 3.0.5 on 2020-04-22 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200421_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='empleo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Empleo'),
        ),
    ]
