# Generated by Django 3.0.5 on 2020-04-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_empleo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recibo',
            name='monto',
        ),
    ]
